### ISSUE TITLE
класс-переводчик

### ISSUE THREAD

**Issue by sslavian812** [sslavian812/web#10]
сделать класс, инкапсулирующий перевод слов и текстов
слова - по словарю,
текст - по яндекс-переводчику

с базой данных для словаря можно напрячь и меня, разберемся.

**Comment by h0tk3y** [comment]
Займусь. Вопрос: нам можно не беспокоиться об асинхронности операций с сетью? Я так понимаю, у нас и так создаётся отдельный поток на каждый запрос (WSGI), и можно его блокировать длительными операциями, если больше нечего делать в это время, верно?

**Comment by h0tk3y** [comment]
Готово, если нужна документация или пояснения, будут.
