### ISSUE TITLE
do servlet

### ISSUE THREAD

**Issue by sslavian812** [sslavian812/web#16]
я возьмусть пока за манипуляции со словам и списками.
по сответсвуюим запросам надо манипулировать словами и списками, уметь отдавать в json'е то, что попросили(список слов, список списков).

**Comment by h0tk3y** [comment]
Я думаю, в БД надо добавить время создания. Полагаю, что в каждой таблице пригодится, но в словах и списках, imho, обязательно, чтобы сортировать по нему.
