### ISSUE TITLE
спроектировать с закодить БД

### ISSUE THREAD

**Issue by sslavian812** [sslavian812/web#6]
используя SQLAlchemy сделать модели для бд.
сущности 
1)юзер 
2)список слов, принадлежащий юзеру 
3)слова? как хранятся слова???
http://habrahabr.ru/post/87210/
^тут пример^

http://docs.sqlalchemy.org/en/latest/index.html
^тут документация^

**Comment by h0tk3y** [comment]
Вот такая структура БД в приложении, ту её часть, которая занимается словарными статьями и списками слов, можно, наверное, почти без изменений переносить.
![DB structure](https://dl.dropboxusercontent.com/u/67860601/HchYvQr5k6w.jpg)

**Comment by sslavian812** [comment]
как-то все очень странно и мутно. чего ж так много-то?
статьи? синонимы? значения? примеры? заметки?

**Comment by sslavian812** [comment]
у меня вышло что-то такое.
![index](https://cloud.githubusercontent.com/assets/4104482/5107279/6a9e053a-7011-11e4-94da-71bee61d71f4.png)

**Comment by h0tk3y** [comment]
Так много там потому, что у Яндекс.Словарей словарные статьи содержат вот эту всю информацию, и сохранить это всё, чтобы потом можно было адекватно вытащить словарную статью в таком же виде, получилось только таким количеством таблиц. Вот у Яндекс.Переводчика в ответе API только текст, там проще.)

**Comment by sslavian812** [comment]
ну ладно, я набросал базу. схема как на картинке, только у списка может быть имя еще
